version: '3.8'

services:
  db-1:
    image: postgres:alpine
    container_name: shard-db-1
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - shard-db-1-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-2:
    image: postgres:alpine
    container_name: shard-db-2
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234
    ports:
      - "6432:5432"
    volumes:
      - shard-db-2-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  shard-db-1-data:
  shard-db-2-data: